spring:
  application:
    name: reactive-microservice

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        sliding-window-size: 4
#        failure-rate-threshold: 50
#        automatic-transition-from-open-to-half-open-enabled: true
#        wait-duration-in-open-state:
#          nanos: 5000
